{% set name = "vtkplotter" %}
{% set version = "2020.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d08058311007c8cbf91157d5eb6ee1811ad31bf48557fd3600936272ce358ebf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - vtk
    - numpy

test:
  imports:
    - vtkplotter

about:
  home: "https://github.com/marcomusy/vtkplotter"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A python module for scientific visualization, analysis and animation of 3D objects and point clouds based on VTK."
  doc_url: https://vtkplotter.embl.es/
  dev_url: https://github.com/marcomusy/vtkplotter

extra:
  recipe-maintainers:
    - RubendeBruin
    - marcomusy
